apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  lables:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq01
    specs:
      containers:
        - name: vpromq01
          image: rabbitmq
          ports:
            - name: vprmq01-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                name: app-secret
                key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"


