apiVersion: app/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLables:
      app: vprodb
  replicas: 1
  template:
    metadata:
      lables:
        app: vprodb
    specs:
      containers:
        - name: vprodb
          image: chaitanya2616/vprofiledb:V1
          args:
          - "ignore-db-dir=lost+fount"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0c3646e88040a3d69
            fsType: ext4

